name: Run ci command on Linux
on:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: Install mediawiki quickstart
      run: git clone https://gitlab.wikimedia.org/repos/qte/mediawiki-quickstart.git
    - name: Run ci command
      env: 
        SILENT: 1
      run: |
        cd mediawiki-quickstart
        ./ci 2>&1 | tee output.log
    - name: Display latest logs
      if: always()
      run: tail -n 100 mediawiki-quickstart/output.log