name: Run ci command on Linux
on:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: Install mediawiki quickstart
      run: git clone https://gitlab.wikimedia.org/mhurd/mediawiki-quickstart.git
    - name: Run ci command
      run: |
        cd mediawiki-quickstart
        ./ci