name: Run fresh install on Linux
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install mediawiki quickstart
      run: | 
        git clone https://gitlab.wikimedia.org/mhurd/mediawiki-quickstart.git
    - name: Run fresh install
      run: |
        cd mediawiki-quickstart
        SILENT=1 SKIP_COUNTDOWN=1 FORCE=1 ./fresh_install
    - name: Install xvfb
      run: sudo apt-get install -y xvfb
    - name: Start xvfb
      run: Xvfb :99 -ac &
    - name: Run Selenium core tests
      run: |
        DISPLAY=:99
        echo $DISPLAY
        cd mediawiki-quickstart
        SILENT=1 ./run_selenium_tests