name: Run fresh install on Linux
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install mediawiki quickstart
      run: | 
        git clone https://gitlab.wikimedia.org/mhurd/mediawiki-quickstart.git
    - name: Run fresh install
      env:
        SILENT: 1
        SKIP_COUNTDOWN: 1 
        FORCE: 1
      run: |
        cd mediawiki-quickstart
        ./fresh_install
        ./install skins/Vector
    - name: Run Selenium core tests
      env: 
        DEBIAN_FRONTEND: noninteractive
        SILENT: 1
        VERBOSE: 1
      run: |
        cd mediawiki-quickstart
        ./run_selenium_tests "tests/selenium/**/specs/**/*.js" ".*" </dev/null